<html lang="es">
<head>
	<title>Joshua Cafe Bar. Encuestas</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Encuesta Joshua</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Puntos</a></li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>
<div class="container">
	<div>
		<h1>Puntos</h1>
		<table id="puntos" class="table table-striped table-bordered">
			<thead>	
				<tr>
					<th>ID</th>
					<th>Nombre</th>
					<th>Latitud</th>
					<th>Longitud</th>
					<th>Código</th>
					<th></th>
				</tr>
			</thead>
			<tbody id="puntosHere">
			</tbody>
		</table>
		<h1>Meseros</h1>
		<table id="meseros" class="table table-striped table-bordered">
			<thead>	
				<tr>
					<th>ID</th>
					<th>Nombre</th>
					<th></th>
				</tr>
			</thead>
			<tbody id="meserosHere">
			</tbody>
		</table>
		<h1>Mesero</h1>
		<form id="meseroForm">
			<label>Id:</label>
			<input name="id" id="mesero_id" type="text" disabled/>
			<label>Nombre:</label>
			<input name="name" id="mesero_name" type="text">
			<a class="btn btn-default" id="mesero_save">Guardar</a>
		</form>
	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="js/encuesta.js"></script>
</body>
</html>
