<html lang="es">
<head>
	<title>Joshua Cafe Bar. Encuestas</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Encuesta Joshua</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="/">Puntos</a></li>
				<li class="active"><a href="/reports.html">Reportes</a></li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>
<div class="container">
	<div>
		<h1>Puntos</h1>
		<p>Haga click en el punto que desea para ver los meseros en la parte inferior</p>
		<table id="puntos" class="table table-striped table-bordered">
			<thead>	
				<tr>
					<th>ID</th>
					<th>Nombre</th>
					<th>Latitud</th>
					<th>Longitud</th>
					<th>Código</th>
					<th></th>
				</tr>
			</thead>
			<tbody id="puntosHere">
			</tbody>
		</table>
		<div id= "section_table">
		<h1>Meseros de <span id="title_punto_nombre"></span></h1>
		<p>Haga click sobre el mesero que desea para modificar la información del mismo en la parte inferior</p>
		<a class="btn btn-primary" onClick="meseroAdd()"><span class="glyphicon glyphicon-plus"></span> Agregar</a>
		<table id="meseros" class="table table-striped table-bordered">
			<thead>	
				<tr>
					<th>ID</th>
					<th>Nombre</th>
					<th></th>
				</tr>
			</thead>
			<tbody id="meserosHere">
			</tbody>
		</table>
		</div>
		<div id="section_form">
		<h1>Mesero</h1>
		<form id="meseroForm" action="/api/picture" method="post" enctype="multipart/form-data">
			<div class="row">
				<input name="locattion" id="mesero_locattion" type="hidden">
				<label>Id:</label>
				<input name="id" id="mesero_id" type="text" readonly/>
			</div>
			<div class="row">		
				<label>Nombre:</label>
				<input name="name" id="mesero_name" type="text">
			</div>
			<div class="row">
				<div class="fileinput fileinput-new" data-provides="fileinput">
					<span class="fileinput-new">
						<img id="mesero_image" width="200px" height="200px"/>
					</span>
					<span class="fileinput-exists">
						<div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 200px;"></div>
					</span>
					<div>
				    	<span class="btn btn-default btn-file"><span class="fileinput-new">Seleccionar</span><span class="fileinput-exists">Cambiar</span><input type="file" name="picture" accept="image/jpeg"></span>
    				    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Eliminar</a>
  					</div>
				</div>
			</div>
		</form>
		<a class="btn btn-default" id="mesero_save">Guardar</a>
	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
<script src="js/encuesta.js"></script>
</body>
</html>
